# Name of this app
service: fizzy
image: fizzy

# Configure the image builder
builder:
  arch: amd64

# Where to deploy fizzy
servers:
  web:
    # - 178.156.199.54 # Public IP
    - 100.100.138.64 # Tailscale IP

# How you connect to your server
ssh:
  user: root

# Automatic SSL
proxy:
  ssl: true
  host: fizzy.angeladames.com

# Your application configuration (secrets come from .kamal/secrets).
env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
  clear:
    BASE_URL: https://fizzy.angeladames.com
    MAILER_FROM_ADDRESS: support@angeladames.com
    SMTP_ADDRESS: mail.example.com
    MULTI_TENANT: false
    SOLID_QUEUE_IN_PUMA: true
    SMTP_ADDRESS: smtp.resend.com
    ACTIVE_STORAGE_SERVICE: s3
    S3_BUCKET: fizzy
    S3_REGION: auto
    S3_FORCE_PATH_STYLE: true
    S3_ENDPOINT: https://39e7b7bcfc65627d3e93428d23a3aafb.r2.cloudflarestorage.com
    S3_REQUEST_CHECKSUM_CALCULATION: when_required
    S3_RESPONSE_CHECKSUM_VALIDATION: when_required
    CSP_CONNECT_SRC: https://*.r2.cloudflarestorage.com

#-- General configuration --#

# Use a local registry to deploy
registry:
  server: localhost:5555

# Handy aliases for interacting with your deployment. For eaxmple: `bin/kamal console` will connect to a
# Rails console in production.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "fizzy_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets
